[package]
name = "aoc22"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "05"
path = "05.rs"

[[bin]]
name = "05p2"
path = "05p2.rs"

[[bin]]
name = "06"
path = "06.rs"

[[bin]]
name = "06p2"
path = "06p2.rs"

[dependencies]
